# Generated by Django 4.2.11 on 2024-11-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vktbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermod',
            table='Tai_khoan',
        ),
    ]
